### ISSUE TITLE
PyPI version not equal to github tag

### ISSUE THREAD

**Issue by tumb1er** [just-work/django-testing-utils#4]
```
    @override_defaults('sitemap_generate', SITEMAP_HOST='123')
    def test_generate_from_param(self):
```

````
Error
Traceback (most recent call last):
  File "/data/cinema/virtualenv/lib/python3.8/site-packages/django/test/utils.py", line 367, in inner
    with self as context:
  File "/data/cinema/virtualenv/lib/python3.8/site-packages/django/test/utils.py", line 335, in __enter__
    return self.enable()
  File "/data/cinema/virtualenv/lib/python3.8/site-packages/django_testing_utils/utils.py", line 37, in enable
    patcher.start()
  File "/usr/lib/python3.8/unittest/mock.py", line 1551, in start
    result = self.__enter__()
  File "/usr/lib/python3.8/unittest/mock.py", line 1416, in __enter__
    original, local = self.get_original()
  File "/usr/lib/python3.8/unittest/mock.py", line 1389, in get_original
    raise AttributeError(
AttributeError: <module 'sitemap_generate' from '/data/cinema/virtualenv/lib/python3.8/site-packages/sitemap_generate/__init__.py'> does not have the attribute 'SITEMAP_HOST'
```

This is because [tagged](https://github.com/just-work/django-testing-utils/blob/0.0.1/django_testing_utils/utils.py#L30) code is not same as code in pypi package:
```
    def enable(self):
        """ Create patchers, start save and start them. """
        for settings, value in self.settings.items():
            patcher = mock.patch(f'{self.module}.{settings}', value)
            self.patchers.append(patcher)
            patcher.start()
```

**Comment by tumb1er** [comment]
0.0.2 released
